### ISSUE TITLE
should wrapper-small be renamed?

### ISSUE THREAD

**Issue by drKnoxy** [cutestrap/cutestrap#26]
I thought `wrapper-small` should be replaced with `wrapper wrapper--small`

even the inline docs hint at this
`<div class="wrapper {{modifier_class}}">Wrapper</div>`

**Comment by csscallum** [comment]
This is something I did in my personal fork so I've created a pull request (https://github.com/cutestrap/cutestrap/pull/28). It also saves a couple of lines of code (every little helps).

**Comment by tylerchilds** [comment]
I had it like that originally, which is why the docs allude to it, but had changed it. Merged in this PR, thanks @csscallum :)

Just getting back from a vacation, so I'll be more active again.
