### ISSUE TITLE
grid implementation

### ISSUE THREAD

**Issue by awinogradov** [cutestrap/cutestrap#31]
You can use [Sharps](http://theprotein.github.io/sharps/gh-pages/index.html) grid for building grid on BEM.

**Comment by tylerchilds** [comment]
Thanks! I'm going to close this for now, since I don't plan on re-writing the grid. I only really put this one in here as a simple and out of the box approach that enables rapid structuring. There are plenty of existing grid systems out there that can seamlessly work alongside cutestrap.
