### ISSUE TITLE
Rem units on body tag

### ISSUE THREAD

**Issue by mynamesleon** [cutestrap/cutestrap#4]
There was a bug in older Chrome where REM units on the body tag weren't applied correctly: https://bugs.chromium.org/p/chromium/issues/detail?id=319623
I'd advise using em or % for the font-size and line-height on the body tag to cater for this just in case

**Comment by tylerchilds** [comment]
I'll update the body to have em, since the bug is just for the body tag, rem in all other locations will go unaffected.

**Comment by tylerchilds** [comment]
This introduced a new bug, where the line-height on the body when sized with em was larger than expected, so it won't be merged. The bug also seems pretty low risk as chrome auto-updates by default.
