### ISSUE TITLE
Use links and buttons in demos instead of spans.

### ISSUE THREAD

**Issue by nattarnoff** [cutestrap/cutestrap#6]
Using `spans` as demonstration for buttons and links promotes using non-semantic elements that aren't accessible without added code that developers get for free with the semantic versions.

Current button/link demo code is 
```
<span class="btn">Default</span>
<span class="btn btn--secondary">Secondary</span>
<span class="btn btn--link">Link</span>
```

I recommend making it:
```
<button class="btn">Default</button>
<button class="btn btn--secondary">Secondary</button>
<a href="#" class="btn btn--link">Link</a>
```

`a` should be used when navigating to another point on the page or another page.
`button` or `<input type="button" />` should be used when taking an action on the page (submitting a form, opening a modal, sorting a table, etc.). The `button` element is preferred as developers can include icons, images, and hidden text to keep them accessible and flexible.

**Comment by tylerchilds** [comment]
Great idea, I'll updated this tonight!

**Comment by tylerchilds** [comment]
resolved
